import { PropDefinition } from "@/components/docs/props-table"

export interface ComponentDefinition {
  name: string
  slug: string
  description: string
  category: string
  importPath: string
  props: PropDefinition[]
  a11y?: string[]
}

export const components: ComponentDefinition[] = [
  // Forms
  {
    name: "Button",
    slug: "button",
    description: "Bouton interactif avec plusieurs variantes et tailles.",
    category: "Forms",
    importPath: "Button",
    props: [
      { name: "variant", type: '"default" | "destructive" | "outline" | "secondary" | "ghost" | "link"', default: '"default"', description: "Le style visuel du bouton" },
      { name: "size", type: '"default" | "sm" | "lg" | "icon"', default: '"default"', description: "La taille du bouton" },
      { name: "asChild", type: "boolean", default: "false", description: "Fusionne les props avec l'enfant" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive le bouton" },
    ],
    a11y: [
      "Supporte la navigation au clavier",
      "Annonce son état aux lecteurs d'écran",
      "Focus visible par défaut",
    ],
  },
  {
    name: "Input",
    slug: "input",
    description: "Champ de saisie de texte standard.",
    category: "Forms",
    importPath: "Input",
    props: [
      { name: "type", type: "string", default: '"text"', description: "Type de l'input HTML" },
      { name: "placeholder", type: "string", description: "Texte indicatif" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive l'input" },
    ],
  },
  {
    name: "Textarea",
    slug: "textarea",
    description: "Zone de texte multiligne.",
    category: "Forms",
    importPath: "Textarea",
    props: [
      { name: "placeholder", type: "string", description: "Texte indicatif" },
      { name: "rows", type: "number", description: "Nombre de lignes visibles" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive le textarea" },
    ],
  },
  {
    name: "Select",
    slug: "select",
    description: "Menu déroulant pour sélectionner une option.",
    category: "Forms",
    importPath: "Select, SelectContent, SelectItem, SelectTrigger, SelectValue",
    props: [
      { name: "value", type: "string", description: "Valeur sélectionnée (contrôlé)" },
      { name: "defaultValue", type: "string", description: "Valeur par défaut (non contrôlé)" },
      { name: "onValueChange", type: "(value: string) => void", description: "Callback lors du changement" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive le select" },
    ],
  },
  {
    name: "Checkbox",
    slug: "checkbox",
    description: "Case à cocher pour les choix binaires.",
    category: "Forms",
    importPath: "Checkbox",
    props: [
      { name: "checked", type: "boolean | 'indeterminate'", description: "État coché" },
      { name: "onCheckedChange", type: "(checked: boolean) => void", description: "Callback lors du changement" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive la checkbox" },
    ],
  },
  {
    name: "RadioGroup",
    slug: "radio-group",
    description: "Groupe de boutons radio pour sélection exclusive.",
    category: "Forms",
    importPath: "RadioGroup, RadioGroupItem",
    props: [
      { name: "value", type: "string", description: "Valeur sélectionnée" },
      { name: "onValueChange", type: "(value: string) => void", description: "Callback lors du changement" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive le groupe" },
    ],
  },
  {
    name: "Switch",
    slug: "switch",
    description: "Interrupteur à bascule pour activer/désactiver.",
    category: "Forms",
    importPath: "Switch",
    props: [
      { name: "checked", type: "boolean", description: "État activé" },
      { name: "onCheckedChange", type: "(checked: boolean) => void", description: "Callback lors du changement" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive le switch" },
    ],
  },
  {
    name: "Slider",
    slug: "slider",
    description: "Curseur pour sélectionner une valeur dans une plage.",
    category: "Forms",
    importPath: "Slider",
    props: [
      { name: "value", type: "number[]", description: "Valeur(s) actuelle(s)" },
      { name: "onValueChange", type: "(value: number[]) => void", description: "Callback lors du changement" },
      { name: "min", type: "number", default: "0", description: "Valeur minimum" },
      { name: "max", type: "number", default: "100", description: "Valeur maximum" },
      { name: "step", type: "number", default: "1", description: "Pas d'incrémentation" },
    ],
  },
  {
    name: "WakaDateTimePicker",
    slug: "datetime-picker",
    description: "Sélecteur de date et heure avancé avec support timezone.",
    category: "Forms",
    importPath: "WakaDateTimePicker",
    props: [
      { name: "value", type: "Date | undefined", description: "Date sélectionnée" },
      { name: "onChange", type: "(date: Date | undefined) => void", description: "Callback lors du changement" },
      { name: "mode", type: '"date" | "time" | "datetime"', default: '"datetime"', description: "Mode de sélection" },
      { name: "placeholder", type: "string", description: "Texte indicatif" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactive le picker" },
    ],
  },
  {
    name: "WakaAutocomplete",
    slug: "autocomplete",
    description: "Champ de recherche avec suggestions automatiques.",
    category: "Forms",
    importPath: "WakaAutocomplete",
    props: [
      { name: "options", type: "Option[]", required: true, description: "Liste des options disponibles" },
      { name: "value", type: "string", description: "Valeur sélectionnée" },
      { name: "onValueChange", type: "(value: string) => void", description: "Callback lors de la sélection" },
      { name: "placeholder", type: "string", description: "Texte indicatif" },
      { name: "emptyMessage", type: "string", default: '"Aucun résultat"', description: "Message si aucune option" },
    ],
  },
  {
    name: "WakaColorPicker",
    slug: "color-picker",
    description: "Sélecteur de couleur avec preview.",
    category: "Forms",
    importPath: "WakaColorPicker",
    props: [
      { name: "value", type: "string", description: "Couleur sélectionnée (hex)" },
      { name: "onChange", type: "(color: string) => void", description: "Callback lors du changement" },
      { name: "presets", type: "string[]", description: "Couleurs prédéfinies" },
    ],
  },
  {
    name: "WakaFileUpload",
    slug: "file-upload",
    description: "Zone de téléchargement de fichiers avec drag & drop.",
    category: "Forms",
    importPath: "WakaFileUpload",
    props: [
      { name: "onFilesSelected", type: "(files: File[]) => void", required: true, description: "Callback avec les fichiers" },
      { name: "accept", type: "string", description: "Types MIME acceptés" },
      { name: "multiple", type: "boolean", default: "false", description: "Autoriser plusieurs fichiers" },
      { name: "maxSize", type: "number", description: "Taille max en bytes" },
    ],
  },
  {
    name: "WakaRichTextEditor",
    slug: "rich-text-editor",
    description: "Éditeur de texte riche avec formatage.",
    category: "Forms",
    importPath: "WakaRichTextEditor",
    props: [
      { name: "value", type: "string", description: "Contenu HTML" },
      { name: "onChange", type: "(value: string) => void", description: "Callback lors du changement" },
      { name: "placeholder", type: "string", description: "Texte indicatif" },
      { name: "toolbar", type: "ToolbarOption[]", description: "Options de la barre d'outils" },
    ],
  },
  {
    name: "Label",
    slug: "label",
    description: "Label accessible pour les champs de formulaire.",
    category: "Forms",
    importPath: "Label",
    props: [
      { name: "htmlFor", type: "string", description: "ID du champ associé" },
    ],
  },

  // Data Display
  {
    name: "Card",
    slug: "card",
    description: "Conteneur flexible pour afficher du contenu.",
    category: "Data Display",
    importPath: "Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter",
    props: [
      { name: "className", type: "string", description: "Classes CSS additionnelles" },
    ],
  },
  {
    name: "Table",
    slug: "table",
    description: "Tableau HTML stylisé.",
    category: "Data Display",
    importPath: "Table, TableBody, TableCell, TableHead, TableHeader, TableRow",
    props: [
      { name: "className", type: "string", description: "Classes CSS additionnelles" },
    ],
  },
  {
    name: "DataTableAdvanced",
    slug: "data-table-advanced",
    description: "Tableau de données avancé avec tri, filtres, pagination et export.",
    category: "Data Display",
    importPath: "DataTableAdvanced",
    props: [
      { name: "columns", type: "ColumnDef<T>[]", required: true, description: "Définition des colonnes" },
      { name: "data", type: "T[]", required: true, description: "Données à afficher" },
      { name: "searchColumn", type: "string", description: "Colonne pour la recherche globale" },
      { name: "enableFiltering", type: "boolean", default: "true", description: "Active les filtres" },
      { name: "enableSorting", type: "boolean", default: "true", description: "Active le tri" },
      { name: "enablePagination", type: "boolean", default: "true", description: "Active la pagination" },
      { name: "pageSize", type: "number", default: "10", description: "Nombre de lignes par page" },
    ],
  },
  {
    name: "Badge",
    slug: "badge",
    description: "Badge pour afficher un statut ou une catégorie.",
    category: "Data Display",
    importPath: "Badge",
    props: [
      { name: "variant", type: '"default" | "secondary" | "destructive" | "outline"', default: '"default"', description: "Style du badge" },
    ],
  },
  {
    name: "Avatar",
    slug: "avatar",
    description: "Avatar pour représenter un utilisateur.",
    category: "Data Display",
    importPath: "Avatar, AvatarImage, AvatarFallback",
    props: [
      { name: "src", type: "string", description: "URL de l'image (AvatarImage)" },
      { name: "alt", type: "string", description: "Texte alternatif (AvatarImage)" },
    ],
  },
  {
    name: "Progress",
    slug: "progress",
    description: "Barre de progression.",
    category: "Data Display",
    importPath: "Progress",
    props: [
      { name: "value", type: "number", description: "Pourcentage de progression (0-100)" },
    ],
  },
  {
    name: "Skeleton",
    slug: "skeleton",
    description: "Placeholder de chargement animé.",
    category: "Data Display",
    importPath: "Skeleton",
    props: [
      { name: "className", type: "string", description: "Classes CSS pour dimensions" },
    ],
  },
  {
    name: "Calendar",
    slug: "calendar",
    description: "Calendrier pour sélectionner une date.",
    category: "Data Display",
    importPath: "Calendar",
    props: [
      { name: "selected", type: "Date | undefined", description: "Date sélectionnée" },
      { name: "onSelect", type: "(date: Date | undefined) => void", description: "Callback lors de la sélection" },
      { name: "mode", type: '"single" | "range" | "multiple"', default: '"single"', description: "Mode de sélection" },
    ],
  },

  // Charts
  {
    name: "WakaBarChart",
    slug: "bar-chart",
    description: "Graphique en barres basé sur Recharts.",
    category: "Charts",
    importPath: "WakaBarChart",
    props: [
      { name: "data", type: "ChartData[]", required: true, description: "Données du graphique" },
      { name: "xKey", type: "string", required: true, description: "Clé pour l'axe X" },
      { name: "yKeys", type: "string[]", required: true, description: "Clés pour l'axe Y" },
      { name: "height", type: "number", default: "300", description: "Hauteur en pixels" },
      { name: "colors", type: "string[]", description: "Couleurs des barres" },
    ],
  },
  {
    name: "WakaLineChart",
    slug: "line-chart",
    description: "Graphique en lignes basé sur Recharts.",
    category: "Charts",
    importPath: "WakaLineChart",
    props: [
      { name: "data", type: "ChartData[]", required: true, description: "Données du graphique" },
      { name: "xKey", type: "string", required: true, description: "Clé pour l'axe X" },
      { name: "yKeys", type: "string[]", required: true, description: "Clés pour l'axe Y" },
      { name: "height", type: "number", default: "300", description: "Hauteur en pixels" },
      { name: "curved", type: "boolean", default: "false", description: "Lignes courbes" },
    ],
  },
  {
    name: "WakaAreaChart",
    slug: "area-chart",
    description: "Graphique en aires basé sur Recharts.",
    category: "Charts",
    importPath: "WakaAreaChart",
    props: [
      { name: "data", type: "ChartData[]", required: true, description: "Données du graphique" },
      { name: "xKey", type: "string", required: true, description: "Clé pour l'axe X" },
      { name: "yKeys", type: "string[]", required: true, description: "Clés pour l'axe Y" },
      { name: "height", type: "number", default: "300", description: "Hauteur en pixels" },
      { name: "stacked", type: "boolean", default: "false", description: "Aires empilées" },
    ],
  },
  {
    name: "WakaPieChart",
    slug: "pie-chart",
    description: "Graphique circulaire basé sur Recharts.",
    category: "Charts",
    importPath: "WakaPieChart",
    props: [
      { name: "data", type: "PieData[]", required: true, description: "Données du graphique" },
      { name: "dataKey", type: "string", required: true, description: "Clé pour les valeurs" },
      { name: "nameKey", type: "string", required: true, description: "Clé pour les labels" },
      { name: "innerRadius", type: "number", default: "0", description: "Rayon intérieur (donut)" },
    ],
  },
  {
    name: "WakaSparkline",
    slug: "sparkline",
    description: "Mini graphique en ligne inline.",
    category: "Charts",
    importPath: "WakaSparkline",
    props: [
      { name: "data", type: "number[]", required: true, description: "Valeurs du sparkline" },
      { name: "width", type: "number", default: "100", description: "Largeur en pixels" },
      { name: "height", type: "number", default: "30", description: "Hauteur en pixels" },
      { name: "color", type: "string", description: "Couleur de la ligne" },
    ],
  },

  // Feedback
  {
    name: "Alert",
    slug: "alert",
    description: "Message d'alerte pour informer l'utilisateur.",
    category: "Feedback",
    importPath: "Alert, AlertTitle, AlertDescription",
    props: [
      { name: "variant", type: '"default" | "destructive"', default: '"default"', description: "Style de l'alerte" },
    ],
  },
  {
    name: "AlertDialog",
    slug: "alert-dialog",
    description: "Dialogue de confirmation avec actions.",
    category: "Feedback",
    importPath: "AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel",
    props: [
      { name: "open", type: "boolean", description: "État ouvert (contrôlé)" },
      { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "Dialog",
    slug: "dialog",
    description: "Fenêtre modale accessible.",
    category: "Feedback",
    importPath: "Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter",
    props: [
      { name: "open", type: "boolean", description: "État ouvert (contrôlé)" },
      { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "Toast",
    slug: "toast",
    description: "Notification temporaire non bloquante.",
    category: "Feedback",
    importPath: "toast, Toaster",
    props: [
      { name: "title", type: "string", description: "Titre du toast" },
      { name: "description", type: "string", description: "Description du toast" },
      { name: "variant", type: '"default" | "destructive"', default: '"default"', description: "Style du toast" },
      { name: "duration", type: "number", default: "5000", description: "Durée en ms" },
    ],
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    description: "Info-bulle au survol.",
    category: "Feedback",
    importPath: "Tooltip, TooltipTrigger, TooltipContent, TooltipProvider",
    props: [
      { name: "content", type: "ReactNode", description: "Contenu de l'info-bulle" },
      { name: "side", type: '"top" | "right" | "bottom" | "left"', default: '"top"', description: "Position" },
    ],
  },
  {
    name: "Popover",
    slug: "popover",
    description: "Panneau flottant déclenché par un élément.",
    category: "Feedback",
    importPath: "Popover, PopoverTrigger, PopoverContent",
    props: [
      { name: "open", type: "boolean", description: "État ouvert (contrôlé)" },
      { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "HoverCard",
    slug: "hover-card",
    description: "Carte de prévisualisation au survol.",
    category: "Feedback",
    importPath: "HoverCard, HoverCardTrigger, HoverCardContent",
    props: [
      { name: "openDelay", type: "number", default: "700", description: "Délai d'ouverture en ms" },
      { name: "closeDelay", type: "number", default: "300", description: "Délai de fermeture en ms" },
    ],
  },

  // Navigation
  {
    name: "Tabs",
    slug: "tabs",
    description: "Navigation par onglets.",
    category: "Navigation",
    importPath: "Tabs, TabsList, TabsTrigger, TabsContent",
    props: [
      { name: "value", type: "string", description: "Onglet actif (contrôlé)" },
      { name: "defaultValue", type: "string", description: "Onglet par défaut" },
      { name: "onValueChange", type: "(value: string) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "NavigationMenu",
    slug: "navigation-menu",
    description: "Menu de navigation avec sous-menus.",
    category: "Navigation",
    importPath: "NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink",
    props: [
      { name: "value", type: "string", description: "Item actif" },
      { name: "onValueChange", type: "(value: string) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "DropdownMenu",
    slug: "dropdown-menu",
    description: "Menu déroulant avec actions.",
    category: "Navigation",
    importPath: "DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator",
    props: [
      { name: "open", type: "boolean", description: "État ouvert (contrôlé)" },
      { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "ContextMenu",
    slug: "context-menu",
    description: "Menu contextuel au clic droit.",
    category: "Navigation",
    importPath: "ContextMenu, ContextMenuTrigger, ContextMenuContent, ContextMenuItem",
    props: [],
  },
  {
    name: "Command",
    slug: "command",
    description: "Palette de commandes avec recherche.",
    category: "Navigation",
    importPath: "Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem",
    props: [
      { name: "value", type: "string", description: "Valeur de recherche" },
      { name: "onValueChange", type: "(value: string) => void", description: "Callback lors de la saisie" },
    ],
  },
  {
    name: "WakaBreadcrumb",
    slug: "breadcrumb",
    description: "Fil d'Ariane pour la navigation.",
    category: "Navigation",
    importPath: "WakaBreadcrumb",
    props: [
      { name: "items", type: "BreadcrumbItem[]", required: true, description: "Items du breadcrumb" },
      { name: "separator", type: "ReactNode", description: "Séparateur personnalisé" },
    ],
  },

  // Layout
  {
    name: "Accordion",
    slug: "accordion",
    description: "Panneaux dépliables.",
    category: "Layout",
    importPath: "Accordion, AccordionItem, AccordionTrigger, AccordionContent",
    props: [
      { name: "type", type: '"single" | "multiple"', default: '"single"', description: "Mode de sélection" },
      { name: "collapsible", type: "boolean", default: "false", description: "Permet de tout fermer (single)" },
    ],
  },
  {
    name: "Collapsible",
    slug: "collapsible",
    description: "Section dépliable simple.",
    category: "Layout",
    importPath: "Collapsible, CollapsibleTrigger, CollapsibleContent",
    props: [
      { name: "open", type: "boolean", description: "État ouvert (contrôlé)" },
      { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "ScrollArea",
    slug: "scroll-area",
    description: "Zone de défilement stylisée.",
    category: "Layout",
    importPath: "ScrollArea, ScrollBar",
    props: [
      { name: "type", type: '"auto" | "always" | "scroll" | "hover"', default: '"hover"', description: "Visibilité des scrollbars" },
    ],
  },
  {
    name: "Sheet",
    slug: "sheet",
    description: "Panneau latéral glissant.",
    category: "Layout",
    importPath: "Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle, SheetDescription",
    props: [
      { name: "side", type: '"top" | "right" | "bottom" | "left"', default: '"right"', description: "Côté d'apparition" },
      { name: "open", type: "boolean", description: "État ouvert (contrôlé)" },
      { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "Separator",
    slug: "separator",
    description: "Ligne de séparation visuelle.",
    category: "Layout",
    importPath: "Separator",
    props: [
      { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Orientation" },
    ],
  },

  // Utilities
  {
    name: "ThemeSelector",
    slug: "theme-selector",
    description: "Sélecteur de thème avec preview.",
    category: "Utilities",
    importPath: "ThemeSelector",
    props: [
      { name: "variant", type: '"default" | "compact"', default: '"default"', description: "Style du sélecteur" },
    ],
  },
  {
    name: "LanguageSelector",
    slug: "language-selector",
    description: "Sélecteur de langue.",
    category: "Utilities",
    importPath: "LanguageSelector",
    props: [
      { name: "variant", type: '"default" | "compact"', default: '"default"', description: "Style du sélecteur" },
    ],
  },
  {
    name: "WakaSpinner",
    slug: "spinner",
    description: "Indicateur de chargement style Jarvis/HUD futuriste avec cercles concentriques animés.",
    category: "Utilities",
    importPath: "WakaSpinner",
    props: [
      { name: "mode", type: '"infinite" | "loading"', default: '"infinite"', description: "Mode d'animation (infinite pour processus continus, loading pour récupération de données)" },
      { name: "label", type: "string", description: "Label affiché au centre du spinner" },
      { name: "subLabel", type: "string", description: "Sous-label affiché sous le label principal" },
      { name: "size", type: '"xs" | "sm" | "md" | "lg" | "xl"', default: '"md"', description: "Taille du spinner" },
      { name: "rings", type: "2 | 3 | 4 | 5", default: "3", description: "Nombre de cercles concentriques" },
      { name: "color", type: '"primary" | "secondary" | "accent" | "destructive" | "muted" | string', default: '"primary"', description: "Couleur principale" },
      { name: "speed", type: "number", default: "3", description: "Vitesse de rotation en secondes" },
      { name: "showParticles", type: "boolean", default: "true", description: "Afficher les particules flottantes" },
      { name: "showPulse", type: "boolean", default: "true", description: "Afficher le pulse central" },
      { name: "ringOpacity", type: "number", default: "0.6", description: "Opacité des anneaux (0-1)" },
    ],
    a11y: [
      "Rôle status avec aria-label",
      "Le label est utilisé comme aria-label si fourni",
    ],
  },
  {
    name: "WakaThemeManager",
    slug: "theme-manager",
    description: "Gestionnaire complet de thèmes avec import/export JSON et prévisualisation.",
    category: "Utilities",
    importPath: "WakaThemeManager",
    props: [
      { name: "onThemeChange", type: "(theme: TweakCNTheme) => void", description: "Callback lors du changement de thème" },
      { name: "onThemeLoad", type: "(theme: TweakCNTheme) => void", description: "Callback lors du chargement d'un thème" },
      { name: "onThemeSave", type: "(theme: TweakCNTheme) => void", description: "Callback lors de la sauvegarde" },
      { name: "initialTheme", type: "TweakCNTheme", description: "Thème initial" },
      { name: "showPreview", type: "boolean", default: "true", description: "Afficher la prévisualisation" },
      { name: "showExport", type: "boolean", default: "true", description: "Afficher l'export" },
      { name: "showImport", type: "boolean", default: "true", description: "Afficher l'import" },
      { name: "allowCustomColors", type: "boolean", default: "true", description: "Autoriser les couleurs personnalisées" },
      { name: "size", type: '"sm" | "base" | "lg" | "full"', default: '"base"', description: "Taille du gestionnaire" },
    ],
  },
  {
    name: "WakaCarousel",
    slug: "carousel",
    description: "Carrousel d'images avec navigation, autoplay et miniatures.",
    category: "Data Display",
    importPath: "WakaCarousel",
    props: [
      { name: "images", type: "CarouselImage[]", required: true, description: "Liste des images" },
      { name: "autoplay", type: "boolean", default: "false", description: "Lecture automatique" },
      { name: "autoplayInterval", type: "number", default: "3000", description: "Intervalle en ms" },
      { name: "showIndicators", type: "boolean", default: "true", description: "Afficher les indicateurs" },
      { name: "showNavigation", type: "boolean", default: "true", description: "Afficher la navigation" },
      { name: "showThumbnails", type: "boolean", default: "false", description: "Afficher les miniatures" },
      { name: "showFullscreen", type: "boolean", default: "false", description: "Afficher le bouton plein écran" },
      { name: "transition", type: '"fade" | "slide" | "zoom" | "flip"', default: '"fade"', description: "Type de transition" },
      { name: "aspectRatio", type: '"16/9" | "4/3" | "1/1" | "3/2" | "auto"', default: '"16/9"', description: "Ratio d'aspect" },
    ],
  },
  {
    name: "WakaNotifications",
    slug: "notifications",
    description: "Centre de notifications avec badge, tabs et actions.",
    category: "Feedback",
    importPath: "WakaNotifications, useNotifications",
    props: [
      { name: "notifications", type: "Notification[]", required: true, description: "Liste des notifications" },
      { name: "onMarkAsRead", type: "(id: string) => void", description: "Callback pour marquer comme lu" },
      { name: "onMarkAllAsRead", type: "() => void", description: "Callback pour tout marquer comme lu" },
      { name: "onDelete", type: "(id: string) => void", description: "Callback pour supprimer" },
      { name: "onDeleteAll", type: "() => void", description: "Callback pour tout supprimer" },
      { name: "showBadge", type: "boolean", default: "true", description: "Afficher le badge" },
      { name: "showTabs", type: "boolean", default: "true", description: "Afficher les onglets" },
      { name: "maxHeight", type: "string", default: '"400px"', description: "Hauteur max de la liste" },
    ],
  },
  {
    name: "WakaAdmincrumb",
    slug: "admincrumb",
    description: "Fil d'Ariane admin avec actions contextuelles.",
    category: "Navigation",
    importPath: "WakaAdmincrumb",
    props: [
      { name: "items", type: "BreadcrumbItem[]", required: true, description: "Items du breadcrumb" },
      { name: "className", type: "string", description: "Classes CSS additionnelles" },
    ],
  },
  {
    name: "InputOTP",
    slug: "input-otp",
    description: "Champ de saisie pour codes OTP.",
    category: "Forms",
    importPath: "InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator",
    props: [
      { name: "maxLength", type: "number", required: true, description: "Nombre de caractères" },
      { name: "value", type: "string", description: "Valeur actuelle" },
      { name: "onChange", type: "(value: string) => void", description: "Callback lors du changement" },
    ],
  },
  {
    name: "Toggle",
    slug: "toggle",
    description: "Bouton à bascule pour les états binaires.",
    category: "Forms",
    importPath: "Toggle",
    props: [
      { name: "pressed", type: "boolean", description: "État pressé" },
      { name: "onPressedChange", type: "(pressed: boolean) => void", description: "Callback lors du changement" },
      { name: "variant", type: '"default" | "outline"', default: '"default"', description: "Style du toggle" },
      { name: "size", type: '"default" | "sm" | "lg"', default: '"default"', description: "Taille du toggle" },
    ],
  },
  {
    name: "AspectRatio",
    slug: "aspect-ratio",
    description: "Conteneur avec ratio d'aspect fixe.",
    category: "Layout",
    importPath: "AspectRatio",
    props: [
      { name: "ratio", type: "number", default: "1", description: "Ratio largeur/hauteur (ex: 16/9)" },
    ],
  },
  {
    name: "Menubar",
    slug: "menubar",
    description: "Barre de menu horizontal avec sous-menus.",
    category: "Navigation",
    importPath: "Menubar, MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem, MenubarSeparator",
    props: [
      { name: "className", type: "string", description: "Classes CSS additionnelles" },
    ],
  },
  {
    name: "Form",
    slug: "form",
    description: "Wrapper de formulaire avec validation react-hook-form.",
    category: "Forms",
    importPath: "Form, FormField, FormItem, FormLabel, FormControl, FormDescription, FormMessage",
    props: [
      { name: "form", type: "UseFormReturn", required: true, description: "Instance de useForm" },
    ],
  },
  {
    name: "Toaster",
    slug: "toaster",
    description: "Conteneur pour afficher les toasts.",
    category: "Feedback",
    importPath: "Toaster",
    props: [],
  },
  {
    name: "Code",
    slug: "code",
    description: "Bloc de code stylisé.",
    category: "Data Display",
    importPath: "Code",
    props: [
      { name: "language", type: "string", description: "Langage de programmation" },
      { name: "showLineNumbers", type: "boolean", default: "false", description: "Afficher les numéros de ligne" },
    ],
  },
  // Waka Components
  {
    name: "WakaStepper",
    slug: "stepper",
    description: "Assistant multi-étapes avec validation, navigation et états.",
    category: "Waka",
    importPath: "WakaStepper, StepperNavigation, useStepperContext",
    props: [
      { name: "steps", type: "Step[]", required: true, description: "Liste des étapes" },
      { name: "currentStep", type: "number", required: true, description: "Index de l'étape courante (0-indexed)" },
      { name: "onStepChange", type: "(stepIndex: number) => void", description: "Callback lors du changement d'étape" },
      { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Orientation du stepper" },
      { name: "variant", type: '"default" | "simple" | "numbered"', default: '"default"', description: "Variante visuelle" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
      { name: "clickable", type: "boolean", default: "false", description: "Autoriser la navigation en cliquant sur les étapes" },
      { name: "allowPrevious", type: "boolean", default: "true", description: "Autoriser uniquement la navigation vers les étapes précédentes" },
      { name: "showContent", type: "boolean", default: "false", description: "Afficher le contenu de l'étape" },
    ],
    a11y: [
      "Navigation au clavier supportée",
      "Aria-current pour l'étape active",
      "Label aria pour la navigation",
    ],
  },
  {
    name: "WakaBreadcrumb",
    slug: "breadcrumb",
    description: "Navigation fil d'Ariane standard avec collapse et personnalisation.",
    category: "Waka",
    importPath: "WakaBreadcrumb, useBreadcrumbFromPath",
    props: [
      { name: "items", type: "BreadcrumbItem[]", required: true, description: "Liste des éléments du fil d'Ariane" },
      { name: "separator", type: "ReactNode", description: "Séparateur entre les éléments" },
      { name: "showHomeIcon", type: "boolean", default: "false", description: "Afficher l'icône Home pour le premier élément" },
      { name: "maxItems", type: "number", description: "Nombre maximum d'éléments visibles (collapse les autres)" },
      { name: "renderLink", type: "(item, children) => ReactNode", description: "Fonction de rendu personnalisée pour les liens" },
      { name: "onItemClick", type: "(item, index) => void", description: "Callback lors du clic sur un élément" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
      { name: "variant", type: '"default" | "ghost" | "outline"', default: '"default"', description: "Variante visuelle" },
    ],
    a11y: [
      "Navigation landmark aria-label",
      "Aria-current pour la page active",
      "Structure sémantique avec ol/li",
    ],
  },
  {
    name: "WakaModal",
    slug: "modal",
    description: "Modal amélioré avec tailles, animations et focus trap.",
    category: "Waka",
    importPath: "WakaModal, useModal, ModalHeader, ModalBody, ModalFooter",
    props: [
      { name: "open", type: "boolean", required: true, description: "État d'ouverture" },
      { name: "onOpenChange", type: "(open: boolean) => void", required: true, description: "Callback de fermeture" },
      { name: "title", type: "string", description: "Titre du modal" },
      { name: "description", type: "string", description: "Description du modal" },
      { name: "size", type: '"sm" | "md" | "lg" | "xl" | "full"', default: '"md"', description: "Taille du modal" },
      { name: "showCloseButton", type: "boolean", default: "true", description: "Afficher le bouton de fermeture" },
      { name: "closeOnOverlayClick", type: "boolean", default: "true", description: "Fermer en cliquant sur l'overlay" },
      { name: "closeOnEscape", type: "boolean", default: "true", description: "Fermer avec la touche Escape" },
      { name: "animation", type: '"fade" | "slide" | "scale" | "none"', default: '"scale"', description: "Animation d'entrée/sortie" },
      { name: "centered", type: "boolean", default: "true", description: "Centré verticalement" },
      { name: "stickyHeader", type: "boolean", default: "false", description: "Header sticky" },
      { name: "stickyFooter", type: "boolean", default: "false", description: "Footer sticky" },
      { name: "footer", type: "ReactNode", description: "Footer avec actions" },
    ],
    a11y: [
      "Focus trap automatique",
      "Fermeture avec Escape",
      "Aria-labelledby et aria-describedby",
      "Focus restauré à la fermeture",
    ],
  },
  {
    name: "WakaTree",
    slug: "tree",
    description: "Vue arborescente avec drag & drop et sélection multiple.",
    category: "Waka",
    importPath: "WakaTree, findNodeById, updateNode, removeNode, addChildNode, moveNode",
    props: [
      { name: "data", type: "TreeNode[]", required: true, description: "Données de l'arbre" },
      { name: "selectedIds", type: "string[]", description: "IDs des noeuds sélectionnés" },
      { name: "onSelect", type: "(ids: string[]) => void", description: "Callback lors de la sélection" },
      { name: "expandedIds", type: "string[]", description: "IDs des noeuds développés" },
      { name: "onExpand", type: "(ids: string[]) => void", description: "Callback lors du développement" },
      { name: "selectionMode", type: '"none" | "single" | "multiple"', default: '"single"', description: "Mode de sélection" },
      { name: "showCheckboxes", type: "boolean", default: "false", description: "Afficher les checkboxes" },
      { name: "showIcons", type: "boolean", default: "true", description: "Afficher les icônes de fichier/dossier" },
      { name: "draggable", type: "boolean", default: "false", description: "Activer le drag & drop" },
      { name: "onDrop", type: "(draggedId, targetId, position) => void", description: "Callback lors du drop" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
      { name: "defaultExpandAll", type: "boolean", default: "false", description: "Développer tout par défaut" },
    ],
    a11y: [
      "Rôle tree avec aria-multiselectable",
      "Aria-expanded pour les noeuds",
      "Aria-selected pour la sélection",
      "Navigation au clavier",
    ],
  },
  {
    name: "WakaPagination",
    slug: "pagination",
    description: "Pagination standalone réutilisable avec options de taille de page.",
    category: "Waka",
    importPath: "WakaPagination, usePagination",
    props: [
      { name: "page", type: "number", required: true, description: "Page courante (1-indexed)" },
      { name: "totalPages", type: "number", required: true, description: "Nombre total de pages" },
      { name: "onPageChange", type: "(page: number) => void", required: true, description: "Callback lors du changement de page" },
      { name: "pageSize", type: "number", default: "10", description: "Nombre d'éléments par page" },
      { name: "pageSizeOptions", type: "number[]", default: "[10, 20, 50, 100]", description: "Options de taille de page" },
      { name: "onPageSizeChange", type: "(size: number) => void", description: "Callback lors du changement de taille" },
      { name: "totalItems", type: "number", description: "Nombre total d'éléments" },
      { name: "showPageSizeSelector", type: "boolean", default: "false", description: "Afficher la sélection de taille" },
      { name: "showItemsInfo", type: "boolean", default: "false", description: "Afficher les infos sur les éléments" },
      { name: "showFirstLast", type: "boolean", default: "true", description: "Afficher les boutons premier/dernier" },
      { name: "maxVisiblePages", type: "number", default: "7", description: "Nombre maximum de pages à afficher" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille des boutons" },
      { name: "variant", type: '"default" | "outline" | "ghost"', default: '"outline"', description: "Variante visuelle" },
    ],
    a11y: [
      "Navigation landmark aria-label",
      "Aria-current pour la page active",
      "Labels aria pour les boutons",
    ],
  },
  {
    name: "WakaTimePicker",
    slug: "time-picker",
    description: "Sélecteur d'heure standalone avec formats 12h/24h.",
    category: "Waka",
    importPath: "WakaTimePicker, useTimePicker",
    props: [
      { name: "value", type: "string", description: "Valeur sélectionnée (format HH:mm ou HH:mm:ss)" },
      { name: "onChange", type: "(value: string) => void", description: "Callback lors du changement" },
      { name: "format", type: '"12h" | "24h"', default: '"24h"', description: "Format d'affichage" },
      { name: "showSeconds", type: "boolean", default: "false", description: "Afficher les secondes" },
      { name: "minuteStep", type: "number", default: "1", description: "Intervalle des minutes" },
      { name: "secondStep", type: "number", default: "1", description: "Intervalle des secondes" },
      { name: "minTime", type: "string", description: "Heure minimum" },
      { name: "maxTime", type: "string", description: "Heure maximum" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactivé" },
      { name: "error", type: "boolean", default: "false", description: "État d'erreur" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
    ],
    a11y: [
      "Saisie clavier supportée",
      "Labels aria pour les colonnes",
      "Boutons avec aria-label",
    ],
  },
  {
    name: "WakaDateRangePicker",
    slug: "date-range-picker",
    description: "Sélecteur de plage de dates avec presets et calendrier double.",
    category: "Waka",
    importPath: "WakaDateRangePicker, useDateRangePicker, defaultPresets",
    props: [
      { name: "value", type: "DateRange", description: "Plage de dates sélectionnée { from, to }" },
      { name: "onChange", type: "(range: DateRange | undefined) => void", description: "Callback lors du changement" },
      { name: "dateFormat", type: "string", default: '"dd/MM/yyyy"', description: "Format d'affichage" },
      { name: "minDate", type: "Date", description: "Date minimum" },
      { name: "maxDate", type: "Date", description: "Date maximum" },
      { name: "showPresets", type: "boolean", default: "true", description: "Afficher les presets" },
      { name: "presets", type: "DateRangePreset[]", description: "Presets personnalisés" },
      { name: "numberOfMonths", type: "number", default: "2", description: "Nombre de mois affichés" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactivé" },
      { name: "error", type: "boolean", default: "false", description: "État d'erreur" },
      { name: "clearable", type: "boolean", default: "true", description: "Permettre de vider la sélection" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
    ],
    a11y: [
      "Calendrier accessible",
      "Navigation au clavier",
      "Annonces de sélection",
    ],
  },
  {
    name: "WakaCombobox",
    slug: "combobox",
    description: "Combobox avec recherche, création d'options et mode multiple.",
    category: "Waka",
    importPath: "WakaCombobox, useCombobox",
    props: [
      { name: "options", type: "ComboboxOption[]", required: true, description: "Options disponibles" },
      { name: "value", type: "T | T[]", description: "Valeur sélectionnée" },
      { name: "onChange", type: "(value: T | T[] | undefined) => void", description: "Callback lors du changement" },
      { name: "multiple", type: "boolean", default: "false", description: "Mode multiple" },
      { name: "creatable", type: "boolean", default: "false", description: "Permettre la création d'options" },
      { name: "onCreate", type: "(inputValue: string) => ComboboxOption | Promise<ComboboxOption>", description: "Callback de création" },
      { name: "onSearch", type: "(query: string) => Promise<ComboboxOption[]>", description: "Recherche asynchrone" },
      { name: "searchDebounce", type: "number", default: "300", description: "Délai de debounce (ms)" },
      { name: "clearable", type: "boolean", default: "true", description: "Permettre de vider la sélection" },
      { name: "maxSelections", type: "number", description: "Nombre maximum de sélections (multiple)" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactivé" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
    ],
    a11y: [
      "Rôle combobox",
      "Aria-expanded et aria-controls",
      "Navigation au clavier dans la liste",
      "Annonces des sélections",
    ],
  },
  {
    name: "WakaDrawer",
    slug: "drawer",
    description: "Panneau latéral avec plusieurs positions et tailles.",
    category: "Waka",
    importPath: "WakaDrawer, useDrawer, DrawerHeader, DrawerBody, DrawerFooter, DrawerTrigger, DrawerClose",
    props: [
      { name: "open", type: "boolean", required: true, description: "État d'ouverture" },
      { name: "onOpenChange", type: "(open: boolean) => void", required: true, description: "Callback de fermeture" },
      { name: "position", type: '"left" | "right" | "top" | "bottom"', default: '"right"', description: "Position du drawer" },
      { name: "size", type: '"sm" | "md" | "lg" | "xl" | "full"', default: '"md"', description: "Taille du drawer" },
      { name: "title", type: "string", description: "Titre du drawer" },
      { name: "description", type: "string", description: "Description du drawer" },
      { name: "showCloseButton", type: "boolean", default: "true", description: "Afficher le bouton de fermeture" },
      { name: "closeOnOverlayClick", type: "boolean", default: "true", description: "Fermer en cliquant sur l'overlay" },
      { name: "closeOnEscape", type: "boolean", default: "true", description: "Fermer avec Escape" },
      { name: "showOverlay", type: "boolean", default: "true", description: "Afficher l'overlay" },
      { name: "footer", type: "ReactNode", description: "Footer avec actions" },
    ],
    a11y: [
      "Focus trap automatique",
      "Fermeture avec Escape",
      "Aria-labelledby et aria-describedby",
      "Focus restauré à la fermeture",
    ],
  },
  {
    name: "WakaNumberInput",
    slug: "number-input",
    description: "Input numérique avec boutons +/- et validation.",
    category: "Waka",
    importPath: "WakaNumberInput, useNumberInput",
    props: [
      { name: "value", type: "number", description: "Valeur actuelle" },
      { name: "onChange", type: "(value: number) => void", description: "Callback lors du changement" },
      { name: "min", type: "number", description: "Valeur minimum" },
      { name: "max", type: "number", description: "Valeur maximum" },
      { name: "step", type: "number", default: "1", description: "Pas d'incrémentation" },
      { name: "precision", type: "number", description: "Nombre de décimales" },
      { name: "buttonPosition", type: '"sides" | "right" | "none"', default: '"sides"', description: "Position des boutons" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactivé" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
    ],
    a11y: [
      "Aria-valuenow, aria-valuemin, aria-valuemax",
      "Navigation au clavier avec flèches",
      "Boutons avec aria-label",
    ],
  },
  {
    name: "WakaImage",
    slug: "image",
    description: "Image avec lazy loading, placeholder et zoom.",
    category: "Waka",
    importPath: "WakaImage, WakaImageGallery",
    props: [
      { name: "src", type: "string", required: true, description: "URL de l'image" },
      { name: "alt", type: "string", required: true, description: "Texte alternatif" },
      { name: "width", type: "number | string", description: "Largeur" },
      { name: "height", type: "number | string", description: "Hauteur" },
      { name: "aspectRatio", type: "string", default: '"16/9"', description: "Ratio d'aspect" },
      { name: "fit", type: '"cover" | "contain" | "fill" | "none"', default: '"cover"', description: "Mode de redimensionnement" },
      { name: "lazy", type: "boolean", default: "true", description: "Chargement lazy" },
      { name: "placeholder", type: '"blur" | "skeleton" | "none"', default: '"skeleton"', description: "Type de placeholder" },
      { name: "zoomable", type: "boolean", default: "false", description: "Activer le zoom" },
      { name: "downloadable", type: "boolean", default: "false", description: "Permettre le téléchargement" },
    ],
    a11y: [
      "Alt texte obligatoire",
      "Loading state annoncé",
      "Zoom accessible au clavier",
    ],
  },
  {
    name: "WakaQRCode",
    slug: "qrcode",
    description: "Générateur de QR code.",
    category: "Waka",
    importPath: "WakaQRCode",
    props: [
      { name: "value", type: "string", required: true, description: "Contenu du QR code" },
      { name: "size", type: "number", default: "200", description: "Taille en pixels" },
      { name: "level", type: '"L" | "M" | "Q" | "H"', default: '"M"', description: "Niveau de correction d'erreur" },
      { name: "bgColor", type: "string", default: '"#ffffff"', description: "Couleur de fond" },
      { name: "fgColor", type: "string", default: '"#000000"', description: "Couleur du QR code" },
      { name: "logo", type: "string", description: "URL du logo central" },
      { name: "showActions", type: "boolean", default: "false", description: "Afficher les boutons d'action" },
    ],
  },
  {
    name: "WakaBarcode",
    slug: "barcode",
    description: "Générateur de code-barres.",
    category: "Waka",
    importPath: "WakaBarcode",
    props: [
      { name: "value", type: "string", required: true, description: "Valeur du code-barres" },
      { name: "format", type: '"CODE128" | "CODE39"', default: '"CODE128"', description: "Format du code-barres" },
      { name: "width", type: "number", default: "2", description: "Largeur des barres" },
      { name: "height", type: "number", default: "100", description: "Hauteur en pixels" },
      { name: "showText", type: "boolean", default: "true", description: "Afficher le texte" },
      { name: "showActions", type: "boolean", default: "false", description: "Afficher les boutons d'action" },
    ],
  },
  {
    name: "WakaVideo",
    slug: "video",
    description: "Lecteur vidéo avec contrôles personnalisés.",
    category: "Waka",
    importPath: "WakaVideo, useVideo",
    props: [
      { name: "src", type: "string | VideoSource[]", required: true, description: "Source(s) de la vidéo" },
      { name: "poster", type: "string", description: "URL du poster" },
      { name: "autoPlay", type: "boolean", default: "false", description: "Lecture automatique" },
      { name: "loop", type: "boolean", default: "false", description: "Boucle" },
      { name: "muted", type: "boolean", default: "false", description: "Muet" },
      { name: "controls", type: "boolean", default: "true", description: "Afficher les contrôles" },
      { name: "aspectRatio", type: "string", default: '"16/9"', description: "Ratio d'aspect" },
      { name: "showFullscreen", type: "boolean", default: "true", description: "Bouton plein écran" },
      { name: "showPlaybackSpeed", type: "boolean", default: "true", description: "Sélecteur de vitesse" },
      { name: "showQualitySelector", type: "boolean", default: "false", description: "Sélecteur de qualité" },
      { name: "onPlay", type: "() => void", description: "Callback lors de la lecture" },
      { name: "onPause", type: "() => void", description: "Callback lors de la pause" },
      { name: "onEnded", type: "() => void", description: "Callback à la fin" },
    ],
    a11y: [
      "Contrôles au clavier",
      "Aria-label sur les boutons",
      "Support du plein écran accessible",
    ],
  },
  {
    name: "WakaVirtualList",
    slug: "virtual-list",
    description: "Liste virtualisée pour les grandes quantités de données.",
    category: "Waka",
    importPath: "WakaVirtualList, useVirtualList",
    props: [
      { name: "items", type: "T[]", required: true, description: "Données à afficher" },
      { name: "itemHeight", type: "number | ((item, index) => number)", required: true, description: "Hauteur des éléments" },
      { name: "height", type: "number", required: true, description: "Hauteur du conteneur" },
      { name: "width", type: "number | string", default: '"100%"', description: "Largeur du conteneur" },
      { name: "overscan", type: "number", default: "3", description: "Éléments pré-rendus" },
      { name: "renderItem", type: "(item, index, style) => ReactNode", required: true, description: "Fonction de rendu" },
      { name: "onEndReached", type: "() => void", description: "Callback à la fin de la liste" },
      { name: "endReachedThreshold", type: "number", default: "200", description: "Seuil en pixels" },
      { name: "isLoading", type: "boolean", default: "false", description: "Indicateur de chargement" },
      { name: "emptyElement", type: "ReactNode", description: "Élément si liste vide" },
    ],
  },
  {
    name: "WakaSegmentedControl",
    slug: "segmented-control",
    description: "Contrôle segmenté alternatif aux boutons radio.",
    category: "Waka",
    importPath: "WakaSegmentedControl, useSegmentedControl",
    props: [
      { name: "options", type: "SegmentOption[]", required: true, description: "Options disponibles" },
      { name: "value", type: "T", description: "Valeur sélectionnée" },
      { name: "onChange", type: "(value: T) => void", description: "Callback lors du changement" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
      { name: "variant", type: '"default" | "pills"', default: '"default"', description: "Variante visuelle" },
      { name: "fullWidth", type: "boolean", default: "false", description: "Prendre toute la largeur" },
      { name: "disabled", type: "boolean", default: "false", description: "Désactivé" },
      { name: "name", type: "string", description: "Nom pour les formulaires" },
    ],
    a11y: [
      "Rôle radiogroup",
      "Aria-checked pour la sélection",
      "Navigation au clavier",
    ],
  },
  {
    name: "WakaKanban",
    slug: "kanban",
    description: "Tableau Kanban avec colonnes drag & drop.",
    category: "Waka",
    importPath: "WakaKanban, useKanban",
    props: [
      { name: "columns", type: "KanbanColumn[]", required: true, description: "Colonnes du tableau" },
      { name: "onColumnsChange", type: "(columns: KanbanColumn[]) => void", description: "Callback lors du changement" },
      { name: "onCardClick", type: "(card: KanbanCard) => void", description: "Callback lors du clic sur une carte" },
      { name: "onCardAdd", type: "(columnId: string) => void", description: "Callback pour ajouter une carte" },
      { name: "onCardDelete", type: "(cardId: string, columnId: string) => void", description: "Callback pour supprimer une carte" },
      { name: "onColumnAdd", type: "() => void", description: "Callback pour ajouter une colonne" },
      { name: "onColumnDelete", type: "(columnId: string) => void", description: "Callback pour supprimer une colonne" },
      { name: "cardDraggable", type: "boolean", default: "true", description: "Cartes déplaçables" },
      { name: "columnDraggable", type: "boolean", default: "false", description: "Colonnes déplaçables" },
      { name: "showAddCard", type: "boolean", default: "true", description: "Afficher le bouton ajouter carte" },
      { name: "showAddColumn", type: "boolean", default: "true", description: "Afficher le bouton ajouter colonne" },
      { name: "showCardCount", type: "boolean", default: "true", description: "Afficher le nombre de cartes" },
    ],
    a11y: [
      "Drag & drop au clavier",
      "Annonces des actions",
      "Labels aria sur les boutons",
    ],
  },
  {
    name: "WakaTimeline",
    slug: "timeline",
    description: "Timeline verticale ou horizontale.",
    category: "Waka",
    importPath: "WakaTimeline",
    props: [
      { name: "items", type: "TimelineItem[]", required: true, description: "Éléments de la timeline" },
      { name: "orientation", type: '"vertical" | "horizontal"', default: '"vertical"', description: "Orientation" },
      { name: "linePosition", type: '"left" | "center" | "right"', default: '"left"', description: "Position de la ligne" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
      { name: "showDates", type: "boolean", default: "true", description: "Afficher les dates" },
      { name: "dateFormat", type: "Intl.DateTimeFormatOptions", description: "Format de date" },
      { name: "collapsible", type: "boolean", default: "false", description: "Éléments collapsibles" },
      { name: "alternate", type: "boolean", default: "false", description: "Alterner les côtés" },
      { name: "onItemClick", type: "(item: TimelineItem) => void", description: "Callback lors du clic" },
    ],
  },
  {
    name: "WakaStat",
    slug: "stat",
    description: "Carte de statistique avec icône, valeur et tendance.",
    category: "Waka",
    importPath: "WakaStat, WakaStatGroup, useStat",
    props: [
      { name: "label", type: "string", required: true, description: "Libellé de la statistique" },
      { name: "value", type: "string | number", required: true, description: "Valeur principale" },
      { name: "description", type: "string", description: "Description ou sous-titre" },
      { name: "icon", type: "ReactNode", description: "Icône à afficher" },
      { name: "trend", type: '"up" | "down" | "neutral"', description: "Direction de la tendance" },
      { name: "trendValue", type: "string", description: 'Valeur de la tendance (ex: "+12%")' },
      { name: "trendText", type: "string", description: 'Texte de la tendance (ex: "vs last month")' },
      { name: "invertTrend", type: "boolean", default: "false", description: "Inverser les couleurs (down=good)" },
      { name: "variant", type: '"default" | "card" | "minimal" | "gradient"', default: '"default"', description: "Variante visuelle" },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille" },
      { name: "color", type: '"default" | "primary" | "success" | "warning" | "destructive" | "blue" | "purple"', default: '"default"', description: "Couleur de l'accent" },
      { name: "loading", type: "boolean", default: "false", description: "État de chargement" },
    ],
  },
  {
    name: "WakaThemeCreator",
    slug: "theme-creator",
    description: "Créateur de thèmes complet avec gestion des ressources (logos, backgrounds) et upload via API.",
    category: "Waka",
    importPath: "WakaThemeCreator, ThemeMetadata, ThemeAssets, ThemeCustomResource, ThemeCreatorApiConfig",
    props: [
      { name: "apiConfig", type: "ThemeCreatorApiConfig", required: true, description: "Configuration de l'API pour l'upload et la sauvegarde" },
      { name: "existingThemes", type: "ThemeMetadata[]", description: "Liste des thèmes existants" },
      { name: "onSaveSuccess", type: "(theme: ThemeMetadata) => void", description: "Callback après sauvegarde réussie" },
      { name: "onDeleteSuccess", type: "(themeId: string) => void", description: "Callback après suppression réussie" },
      { name: "className", type: "string", description: "Classes CSS additionnelles" },
    ],
    a11y: [
      "Navigation au clavier entre les onglets",
      "Labels descriptifs sur tous les champs",
      "Messages de feedback accessibles",
    ],
  },
]

export function getComponentBySlug(slug: string): ComponentDefinition | undefined {
  return components.find((c) => c.slug === slug)
}

export function getComponentsByCategory(category: string): ComponentDefinition[] {
  return components.filter((c) => c.category === category)
}

export const categories = [
  "Forms",
  "Data Display",
  "Charts",
  "Feedback",
  "Navigation",
  "Layout",
  "Utilities",
  "Waka",
]
